package com.backsource.decathlon.types;

public enum ResultChallenge {
	CHALLENGE_100M,
	CHALLANGE_LONG_JUMP,
	CHALLENGE_SHOT_PUT,
	CHALLENGE_HIGH_JUMP,
	CHALLENGE_400M,
	CHALLENGE_110M_HURLES,
	CHALLENGE_DISCUS_THROW,
	CHALLENGE_POLE_VAULT,
	CHALLENGE_JAVELIN_THROW,
	CHALLENGE_1500M
}